// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/config/products/api/data_source/remote/products_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/config/products/api/products_api_client.dart' as _i3;
import 'package:flower_app/config/products/data/model/response/products_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductsResponse_0 extends _i1.SmartFake
    implements _i2.ProductsResponse {
  _FakeProductsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsApiClient extends _i1.Mock implements _i3.ProductsApiClient {
  MockProductsApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProductsResponse> getProducts(Map<String, dynamic>? queries) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [queries]),
            returnValue: _i4.Future<_i2.ProductsResponse>.value(
              _FakeProductsResponse_0(
                this,
                Invocation.method(#getProducts, [queries]),
              ),
            ),
          )
          as _i4.Future<_i2.ProductsResponse>);
}
