// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/presentation/manager/login/login_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/config/error_handling/result.dart' as _i4;
import 'package:flower_app/features/auth/domain/entities/auth_entity.dart'
    as _i5;
import 'package:flower_app/features/auth/domain/use_case/login_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i2.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.AuthEntity>> call({
    required String? email,
    required String? password,
    required bool? rememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #password: password,
              #rememberMe: rememberMe,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.AuthEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthEntity>>(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                  #rememberMe: rememberMe,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthEntity>>);
}
