// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/data/repositories/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/config/error_handling/result.dart' as _i4;
import 'package:flower_app/config/secure_cache/secure_cache/secure_cache.dart'
    as _i8;
import 'package:flower_app/features/auth/api/data_source/remote/auth_remote_data_source_impl.dart'
    as _i2;
import 'package:flower_app/features/auth/data/model/request/register_request.dart'
    as _i7;
import 'package:flower_app/features/auth/data/model/response/auth_response.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSourceImpl extends _i1.Mock
    implements _i2.AuthRemoteDataSourceImpl {
  MockAuthRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.AuthResponse>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i3.Future<_i4.Result<_i5.AuthResponse>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthResponse>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthResponse>>);

  @override
  _i3.Future<_i4.Result<_i5.AuthResponse>> register({
    required _i7.RegisterRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {#request: request}),
            returnValue: _i3.Future<_i4.Result<_i5.AuthResponse>>.value(
              _i6.dummyValue<_i4.Result<_i5.AuthResponse>>(
                this,
                Invocation.method(#register, [], {#request: request}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AuthResponse>>);
}

/// A class which mocks [SecureCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureCache extends _i1.Mock implements _i8.SecureCache {
  MockSecureCache() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveData({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#saveData, [], {#key: key, #value: value}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getData({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [], {#key: key}),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> removeData({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#removeData, [], {#key: key}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
