// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/forget_password/api/forget_password_remote_data_source_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/features/forget_password/api/client/forget_password_client.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ForgetPasswordClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordClient extends _i1.Mock
    implements _i2.ForgetPasswordClient {
  MockForgetPasswordClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> forgetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [email]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> resetPassword(String? email, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email, newPassword]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> verifyReset(String? resetCode) =>
      (super.noSuchMethod(
            Invocation.method(#verifyReset, [resetCode]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
