// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHChjWy3Qf9LfYb1JemsjmJj4YSud4Tf0',
    appId: '1:1035074510871:web:af72154623b82c7c0c3c52',
    messagingSenderId: '1035074510871',
    projectId: 'elevate-flower-app-92318',
    authDomain: 'elevate-flower-app-92318.firebaseapp.com',
    storageBucket: 'elevate-flower-app-92318.firebasestorage.app',
    measurementId: 'G-DWZER0QBKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVF6k1Fz7aa9OgfpSwqEyJwGvVDlu2_ps',
    appId: '1:1035074510871:android:0061ef9392b42fb30c3c52',
    messagingSenderId: '1035074510871',
    projectId: 'elevate-flower-app-92318',
    storageBucket: 'elevate-flower-app-92318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHM48UlRvGVR0UPIazn6Sw8zO4bdvp9qQ',
    appId: '1:1035074510871:ios:6649438b1a97bf670c3c52',
    messagingSenderId: '1035074510871',
    projectId: 'elevate-flower-app-92318',
    storageBucket: 'elevate-flower-app-92318.firebasestorage.app',
    iosBundleId: 'com.example.flowerApp',
  );
}
